"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


first_num = 1
second_num = 1
new_fib = first_num + second_num
sum = 0 

while new_fib < 4 * 10 ** 6:
    sum += new_fib
    first_num = second_num + new_fib
    second_num = new_fib + first_num
    new_fib = first_num + second_num
    
print(sum)

    ### Answer is 4613732 ###